import Head from "next/head";
import User from "../Components/AboutUser";
import Navbar from "../Components/Navbar";
import styles from "../styles/Home.module.css";
import Feed from "../Components/Feed";
import MoreInfo from "../Components/MoreInfo";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Feed | LinkedIn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <User />
        <Feed />
        <MoreInfo />
      </main>
    </div>
  );
}
